### ISSUE TITLE
ItemBoxEncountRateEvent返回无效

### ISSUE THREAD

**Issue by Mcrocarpus** [Muscipular/cgmsv-lua#111]
function ModuleBase:ItemBoxEncountRateEvent(charaIndex, mapId, floor, X, Y, itemIndex)
  print('ItemBoxEncountRateEvent', charaIndex, mapId, floor, X, Y, itemIndex)
  print(Item.GetData(itemIndex, CONST.道具_名字))
  return {1, 30, 10}
end

返回不能改变战斗的怪物

**Comment by Muscipular** [comment]
ItemBoxEncountRate只是修改遇敌概率，不修改遇敌
