### ISSUE TITLE
ItemBoxGenerateEvent返回报错

### ISSUE THREAD

**Issue by Mcrocarpus** [Muscipular/cgmsv-lua#112]
function ModuleBase:ItemBoxGenerateEvent(mapId, floor, itemBoxType, adm)
  print('ItemBoxGenerateEvent', mapId, floor, itemBoxType, adm)
  return {itemBoxType, 13}
end

![QQ图片20230702220435](https://github.com/Muscipular/cgmsv-lua/assets/133592003/26300a16-0131-4cdb-84e7-b0701560aa7a)
宝箱生成的adm中可以大于10

但是adm返回13时会报错
![QQ截图20230702214516](https://github.com/Muscipular/cgmsv-lua/assets/133592003/6ca441d4-e780-4435-aeb3-3dd35692c807)

**Comment by Muscipular** [comment]
建议原样返回
