### ISSUE TITLE
gmsv_hook能开源吗？

### ISSUE THREAD

**Issue by cqkkxili** [Muscipular/cgmsv-lua#116]
登陆后退出再进后台报错不只能不能开源这个文件方便自己修改一下

![L(RR0~9}1AD0P $ N~FGZEL](https://github.com/Muscipular/cgmsv-lua/assets/5636089/8cdb7a0d-fb49-4af9-bfe3-25afa6245b5c)

**Comment by Muscipular** [comment]
https://bbs.cgmsv.com/thread-1363-1-1.html

**Comment by cqkkxili** [comment]
这个需要金币。金币才用完了。他这金币又只能原创等方式获得。没有途径获取金币
