### ISSUE TITLE
3个类别的属性计算事件建议源码上增加血魔计算

### ISSUE THREAD

**Issue by Piaoxue2023** [Muscipular/cgmsv-lua#124]
3个类别的属性计算事件建议增加血魔计算，像套装事件那样，血魔会根据修改后的血魔上限值计算实际血魔值
举例：比如登陆前血2000，登陆时带套装计算血上限是1000，登陆后血变成1000（正常）
           如果登陆时，利用属性的计算事件修改血上限为2000，登陆后血上限会变更成2000，但是血仍然是1000，不会变成2000

**Comment by Muscipular** [comment]
事件中自行处理血量变化
