### ISSUE TITLE
宠装：双击高等级宠装，宠物会假消失

### ISSUE THREAD

**Issue by Piaoxue2023** [Muscipular/cgmsv-lua#125]
**描述问题**
宠装：双击高等级宠装，宠物会假消失，重新登陆，宠物会显示

**问题重现步骤**
1. 打开宠装界面
2. 双击高等级宠装

**截图**
如有有截图请提供截图

**版本信息:**
 - 系统: Win7
 - 引擎版本: 7196540 28bbbb3
 - 框架版本:0.2.31

**Comment by Muscipular** [comment]
无法重现
