### ISSUE TITLE
套装suitset.txt 设置skill替换无效。

### ISSUE THREAD

**Issue by M-Superlove** [Muscipular/cgmsv-lua#134]
skill替换以后。进游戏会有文本提示套装效果。但实际无效

51	陨石变风刃	1	0	19	2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2710,2711,2712,2713,2714,	100	1	635733,	陨石魔法变成风刀魔法	2										5000																			

另：宠物装备无套装效果

**Comment by Muscipular** [comment]
宠物装备无套装效果属于正常现象
