### ISSUE TITLE
宠物负重计算问题

### ISSUE THREAD

**Issue by Mcrocarpus** [Muscipular/cgmsv-lua#143]
local petIndex = Char.GetPet(player, 0)
local itemIndex = Char.GetItemIndex(player, 8)
itemIndex = Item.MakeItem(Item.GetData(itemIndex,CONST.道具_ID))
    if itemIndex >= 0 then
      Item.SetData(itemIndex, CONST.道具_已鉴定, 1)
      Char.SetItemIndex(petIndex, 4, itemIndex)
    end
Pet.UpPet(player,petIndex)
local n1 = Char.GetData(petIndex, CONST.宠物_Weight)
local n2 = Char.GetData(petIndex, CONST.宠物_MaxWeight)

使用lua模拟给宠物穿装备，宠物的负重会减少该宠物装备的负重值（即穿上该装备后，负重没有变化，但是脱掉装备负重减少对应值）

**Comment by Muscipular** [comment]
请使用`Char.MoveItem`
