### ISSUE TITLE
NLG.WalkMove(CharIndex, Dir)BUG

### ISSUE THREAD

**Issue by Mcrocarpus** [Muscipular/cgmsv-lua#54]
己方视角角色不会动，

其他人视角人物每次执行一下次移动时，会先返回上一步的起点，然后再移动，
比如输入指令让角色走  下->下->下,实际角色走的是  下->上->下->上->下

配合upchar时会瞬间完成移动动作，产生类似瞬移效果，以前使用的时候不会

**Comment by Muscipular** [comment]
试试 Char.MoveArray

**Comment by Mcrocarpus** [comment]
Char.MoveArray可以正常使用，在本人视角人物是不动的，但是在别人视角是移动的，
本人视角点击鼠标时会角色会瞬间刷新到移动过后的位置

**Comment by Muscipular** [comment]
仅对NPC/假人有效，cg限制的
