### ISSUE TITLE
NL.RegItemDropEvent

### ISSUE THREAD

**Issue by Piaoxue2023** [Muscipular/cgmsv-lua#64]
白皮书：返回值小于0则拦截丢弃,返回大于等于0则正常丢弃。
实际拦截无效

function 测试:道具丢弃(玩家, 道具)
		print('道具丢弃', 玩家, 道具)
	return -1
end

function 测试:onLoad()
	self:logInfo('load')
	self:regCallback('ItemDropEvent', Func.bind(self.道具丢弃, self));
end

**Comment by Muscipular** [comment]
使用NL.RegPreItemDropEvent代替
