### ISSUE TITLE
NL.RegItemPickUpEvent

### ISSUE THREAD

**Issue by Piaoxue2023** [Muscipular/cgmsv-lua#65]
道具丢地，开启捡起拦截，地上道具可以一直捡

白皮书：返回值小于0则拦截拾取,返回大于等于0则正常拾取。

function 测试:道具捡起(玩家, 道具)
	print('道具捡起', 玩家, 道具)
	return -1
end

function 测试:onLoad()
	self:logInfo('load')
	self:regCallback('ItemPickUpEvent', Func.bind(self.道具捡起, self));
end

**Comment by Muscipular** [comment]
ItemPickUp 不会拦截，请使用PreItemPickUpEvent
