### ISSUE TITLE
Data缺少encount相关项

### ISSUE THREAD

**Issue by Mcrocarpus** [Muscipular/cgmsv-lua#72]
function Data.GetEncountIndex(encountId) end

function Data.GetEncountData(encountIndex, dataPos) end

function Data.SetEncountData(encountIndex, dataPos,val) end

**Comment by Muscipular** [comment]
[+] Data.GetEncountIndex
[+] Data.GetEncountData
[+] Data.SetEncountData
[+] CONST.ENCOUNT_*
