### ISSUE TITLE
NL.RegItemOverLapEvent的回调函数的第四参数传递错误

### ISSUE THREAD

**Issue by Piaoxue2023** [Muscipular/cgmsv-lua#82]
NL.RegItemOverLapEvent
ItemOverLapEventCallBack(CharIndex, FromItemIndex, TargetItemIndex, Num)

根据白皮书的说明：第四参数传递是是FromItemIndex的数量，但实际值是-1

**Comment by Piaoxue2023** [comment]
/

**Comment by Piaoxue2023** [comment]
这个参数只对有堆叠的道具有效，无堆叠的都是-1

**Comment by Muscipular** [comment]
-1为整组
